
REGISTER = @{ "R" ~ ( "1" ~ '0'..'5' | '0'..'9' ) }
REGISTER_KEYWORD = {"STO" | "LOAD" | "ADD" | "SUB" | "STYX"}

PROGRAM = {(STMT)+}

STMT = { STMT_REG | STMT_IM | STMT_ADDR } 
STMT_REG = @{ REGISTER_KEYWORD ~ WHITESPACE ~ REGISTER ~ WHITESPACE ~ REGISTER ~ EOL }
STMT_IM = @{("LOAD" | "CMP") ~ WHITESPACE ~ REGISTER ~ WHITESPACE ~ number ~ EOL }
STMT_ADDR = @{("JMP") ~ WHITESPACE ~  address ~ EOL }
EOL = {("\r\n" | NEWLINE)}

WHITESPACE = _{ " " | "\t" }

number = @{ sign? ~ positive }

sign = { "-" }

positive = {
      "25" ~ '0'..'5'
    | "2"  ~ '0'..'4' ~ '0'..'9'
    | "1"  ~ '0'..'9' ~ '0'..'9'
    | '1'..'9' ~ '0'..'9'
    | '1'..'9'
    | "0"
}

address = @{
    "4096"                      // Matches the exact upper bound
  | "409" ~ '0'..'5'            // Matches 4090 to 4095
  | "40" ~ '0'..'8' ~ '0'..'9'  // Matches 4000 to 4089
  | '1'..'3' ~ ASCII_DIGIT{3}   // Matches 1000 to 3999 (using built-in ASCII_DIGIT)
  | '1'..'9' ~ ASCII_DIGIT{2}   // Matches 100 to 999
  | '1'..'9' ~ ASCII_DIGIT      // Matches 10 to 99
  | ASCII_DIGIT                 // Matches 0 to 9 (using built-in ASCII_DIGIT)
}
