REGISTER = @{ "R" ~ ( "1" ~ '0'..'5' | '0'..'9' ) }
REGISTER_KEYWORD = {"ADD" | "SUB" | "STYX"}

PROGRAM = {(COMMENT | WHITESPACE)* ~ (STMT ~ (COMMENT | WHITESPACE)*)+}
COMMENT = {";" ~ (!EOL ~ ANY)*}
STMT = { STMT_REG | STMT_IM | STMT_ADDR | STMT_LABEL | LABEL_DEC}

LABEL_DEC = @{ASCII_ALPHA+ ~ ":" ~ EOL}
LABEL_USE = @{ASCII_ALPHA+}

STMT_REG = @{ REGISTER_KEYWORD ~ WHITESPACE ~ REGISTER ~ WHITESPACE ~ REGISTER ~ WHITESPACE? ~ COMMENT? ~ EOL }
STMT_IM = @{("LOAD" | "CMP") ~ WHITESPACE ~ REGISTER ~ WHITESPACE ~ number ~ WHITESPACE? ~ COMMENT? ~ EOL }
STMT_ADDR = @{("JMP") ~ WHITESPACE ~  address ~ WHITESPACE? ~ COMMENT? ~ EOL}
STMT_LABEL = @{("JMP") ~ WHITESPACE ~  LABEL_USE ~ WHITESPACE? ~ COMMENT? ~ EOL}

EOL = {("\r\n" | NEWLINE)}

WHITESPACE = _{ " " | "\t" }

number = @{ sign? ~ positive }

sign = { "-" }

positive = {
      "25" ~ '0'..'5'
    | "2"  ~ '0'..'4' ~ '0'..'9'
    | "1"  ~ '0'..'9' ~ '0'..'9'
    | '1'..'9' ~ '0'..'9'
    | '1'..'9'
    | "0"
}

address = @{
    "4096"
  | "409" ~ '0'..'5'
  | "40" ~ '0'..'8' ~ '0'..'9'
  | '1'..'3' ~ ASCII_DIGIT{3}
  | '1'..'9' ~ ASCII_DIGIT{2}
  | '1'..'9' ~ ASCII_DIGIT
  | ASCII_DIGIT
}
