
use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "assembler.pest"]
pub struct AssemblerParser;

use pest::iterators::{Pair, Pairs};
use std::str::FromStr; // Needed for parse::<T>()
                       //
                       //
mod emulator;

// Assume your Rule enum and AssemblerParser struct are defined and generated by Pest
// #[derive(Parser)]
// #[grammar = "path/to/your_grammar.pest"] // Specify the path to your pest file
// struct AssemblerParser;

// #[derive(Rule_Helper)] // If you use rule_helper
// enum Rule { ... }

// Define data structures to represent your instructions
#[derive(Debug)]
struct Instruction {
  mnemonic: String,
  location: u16,
  operand1: Option<Operand>,
  operand2: Option<Operand>,
}

#[derive(Debug)]
enum Operand {
  Register(u8),
  Immediate(i32), // Use i32 for potentially signed numbers from your 'number' rule
  Address(u16),
  Label(String),
}

// --- Helper functions to parse operand strings ---

// Parses a register string like "R1" or "R10"
fn parse_register(reg_str: &str) -> Result<u8, String> {
  if !reg_str.starts_with('R') {
    return Err(format!(
      "Invalid register format: must start with 'R', got '{}'",
      reg_str
    ));
  }
  reg_str[1..]
    .parse::<u8>() // Parse the number part after 'R'
    .map_err(|e| format!("Invalid register number '{}': {}", reg_str, e))
}

// Parses a number string (assuming decimal for simplicity, needs extension for hex)
fn parse_number(num_str: &str) -> Result<i32, String> {
  // Your 'number' rule allows a sign and uses your 'positive' rule.
  // This simple parse handles decimal signed integers.
  // You would need to add logic here to handle hexadecimal if allowed by your 'number' rule
  // (e.g., check for "0x" prefix and parse accordingly).
  i32::from_str(num_str).map_err(|e| format!("Invalid number format '{}': {}", num_str, e))
}

// Parses an address string (assuming decimal for simplicity, needs extension for hex)
fn parse_address(addr_str: &str) -> Result<u16, String> {
  // Your 'address' rule defines the valid range 0-4096 and patterns.
  // This simple parse handles decimal.
  // You would need to add logic here to handle hexadecimal addresses like 0x008 if allowed.
  u16::from_str(addr_str).map_err(|e| format!("Invalid address format '{}': {}", addr_str, e))
}

// --- Main function to process the parse tree ---

fn process_parse_tree(pairs: Pairs<Rule>) -> Result<Vec<Instruction>, String> {
  let mut location: u16 = 0;
  let mut instructions: Vec<Instruction> = Vec::new();

  // Get the single top-level Pair for the PROGRAM rule
  let mut program_pairs = pairs;
  let program_pair = program_pairs
    .next()
    .ok_or("Expected PROGRAM rule at top level")?;

  if program_pair.as_rule() != Rule::PROGRAM {
    return Err(format!(
      "Expected top-level rule PROGRAM, but got {:?}",
      program_pair.as_rule()
    ));
  }
  if program_pairs.next().is_some() {
    return Err("Expected only one top-level PROGRAM pair".to_string());
  }

  // Iterate over the inner pairs matched by the PROGRAM rule (these should be STMT rules)
  let statement_pairs = program_pair.into_inner();

  for stmt_pair in statement_pairs {
    println!("stmt_pair: {:?}", stmt_pair.as_str());
    // Each inner pair of PROGRAM should be a STMT rule based on your grammar PROGRAM = {(STMT)+}
    // If your PROGRAM rule allowed other things like EOL or WHITESPACE directly, you'd check here
    if stmt_pair.as_rule() != Rule::STMT {
      return Err(format!(
        "Expected STMT rule inside PROGRAM, but got {:?}",
        stmt_pair.as_rule()
      ));
    }

    // A STMT pair should have exactly one inner pair: either STMT_REG, STMT_IM, or STMT_ADDR
    let mut stmt_inner_pairs = stmt_pair.into_inner();
    let statement_type_pair = stmt_inner_pairs
      .next()
      .ok_or("Expected statement type rule inside STMT")?;

    if stmt_inner_pairs.next().is_some() {
      // This should not happen based on STMT = { STMT_REG | STMT_IM | STMT_ADDR }
      return Err(format!(
        "Unexpected multiple inner rules for STMT: {:?}",
        statement_type_pair.as_rule()
      ));
    }

    // Now, 'statement_type_pair' is the Pair for STMT_REG, STMT_IM, or STMT_ADDR
    // Since these rules are atomic, we get the full matched string from their span
    let statement_str = statement_type_pair.as_span().as_str().trim(); // Trim trailing EOL for easier splitting

    // --- Process the string based on the matched statement type ---
    let instruction = match statement_type_pair.as_rule() {
      Rule::STMT_REG => {
        // Format: REGISTER_KEYWORD WHITESPACE REGISTER WHITESPACE REGISTER EOL
        // Example string: "STO R1 R2"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 3 {
          return Err(format!(
            "Invalid STMT_REG format string: Expected 3 parts, got '{}'",
            statement_str
          ));
        }
        let mnemonic = parts[0].to_string();
        let reg1 = parse_register(parts[1])?;
        let reg2 = parse_register(parts[2])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Register(reg1)),
          operand2: Some(Operand::Register(reg2)),
        }
      }
      Rule::STMT_IM => {
        // Format: ("LOAD" | "CMP") WHITESPACE REGISTER WHITESPACE number EOL
        // Example string: "LOAD R10 10"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 3 {
          return Err(format!(
            "Invalid STMT_IM format string: Expected 3 parts, got '{}'",
            statement_str
          ));
        }
        let mnemonic = parts[0].to_string();
        let reg = parse_register(parts[1])?;
        let immediate = parse_number(parts[2])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Register(reg)),
          operand2: Some(Operand::Immediate(immediate)),
        }
      }
      Rule::STMT_ADDR => {
        // Format: ("JMP") WHITESPACE address EOL
        // Example string: "JMP 8" or "JMP 1024"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 2 {
          return Err(format!(
            "Invalid STMT_ADDR format string: Expected 2 parts, got '{}'",
            statement_str
          ));
        }
        let mnemonic = parts[0].to_string();
        let address = parse_address(parts[1])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Address(address)),
          operand2: None, // JMP usually has only one operand
        }
      }
      Rule::STMT_LABEL => {
        // Format: ("JMP") WHITESPACE address EOL
        // Example string: "JMP 8" or "JMP 1024"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 2 {
          return Err(format!(
            "Invalid STMT_ADDR format string: Expected 2 parts, got '{}'",
            statement_str
          ));
        }
        let mnemonic = parts[0].to_string();
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Label(parts[1].to_string())),
          operand2: None, // JMP usually has only one operand
        }
      }
      Rule::LABEL_DEC => {
        // Format: ASCII_ALPHA: EOL
        // Example loop:
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 1 {
          return Err(format!(
            "Invalid LABEL format string: Expected 1 part, got '{}'",
            statement_str
          ));
        }
        let mnemonic = parts[0].to_string();
        println!("label: {}", mnemonic);
        // This does not get translated into byte code
        location -= 2;
        Instruction {
          mnemonic,
          location,
          operand1: None,
          operand2: None, // JMP usually has only one operand
        }
      }
      _ => {
        // This case should theoretically not be reached if STMT only alternates the above
        return Err(format!(
          "Unexpected rule type matched as statement type: {:?}",
          statement_type_pair.as_rule()
        ));
      }
    };
    location += 2;
    instructions.push(instruction);
  }

  Ok(instructions)
}

fn main() {
  let fibonacci_program_no_comments_asm = r#"LOAD R0 1
LOAD R1 1
LOAD R5 5
LOAD R6 1
SUB R5 R6
loop:
LOAD R3 R0
ADD R0 R1
LOAD R1 R3
STYX R5 R1
JMP loop
    "#;

  let parse_result = AssemblerParser::parse(Rule::PROGRAM, fibonacci_program_no_comments_asm);

  match parse_result {
    Ok(pairs) => {
      println!("Parse successful. Processing tree...");
      // Process the parse tree
      match process_parse_tree(pairs) {
        Ok(instructions) => {
          println!("Successfully extracted instructions:");
          for instr in instructions {
            println!("{:?}", instr);
          }
        }
        Err(e) => {
          eprintln!("Error processing parse tree: {}", e);
        }
      }
    }
    Err(e) => {
      eprintln!("Parse error: {}", e);
    }
  }
  //println!("{:?}",AssemblerParser::parse(Rule::number, "255"));
  //println!("{:?}",AssemblerParser::parse(Rule::STMT_REG, "STO R1 R2\r\n"));
  //println!("{:?}",AssemblerParser::parse(Rule::STMT_REG, "STO R1 R2\r\n"));
  //println!("{:?}",AssemblerParser::parse(Rule::STMT, "LOAD R1 R2\n"));
  //println!("{:?}",AssemblerParser::parse(Rule::STMT, "LOAD R3 R2\n"));
  //println!("{:?}",AssemblerParser::parse(Rule::STMT, "LOAD R9 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::REGISTER, "R8"));
  //println!("{:?}", AssemblerParser::parse(Rule::REGISTER, "R10"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "STO R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "STO R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "LOAD R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "STYX R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_IM, "LOAD R10 10\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_IM, "LOAD R10 8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_IM, "CMP R10 8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "CMP R10 8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "ADD R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_ADDR, "JMP 1024\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "JMP 1024\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, fibonacci_program_no_comments_asm));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT, "LOAD R10 R8\nSTO R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::PROGRAM, "LOAD R10 R8\nSTO R10 R8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::PROGRAM, fibonacci_program_no_comments_asm));
  //println!("{:?}", AssemblerParser::parse(Rule::LABEL_DEC, "loop:\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_ADDR, "JMP 8\n"));
  //println!("{:?}", AssemblerParser::parse(Rule::STMT_ADDR, "JMP loop\n"));

  //let path = Path::new("hello.bin");
  //let display = path.display();

  //// Open the path in read-only mode, returns `io::Result<File>`
  //let mut file = match File::open(&path) {
  //    Err(why) => panic!("couldn't open {}: {}", display, why),
  //    Ok(file) => file,
  //};

  //let mut cpu = CPU {
  //  registers: [0; 16],
  //  memory: [0; 4096],
  //  position_in_memory: 0,
  //  stack: [0; 16],
  //  stack_pointer: 0,
  //};

  //file.read(&mut cpu.memory).expect("Error reading file");

  //println!("{:?}", cpu.memory);
}

