use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "assembler.pest"]
pub struct AssemblerParser;

use pest::iterators::Pairs;
use std::str::FromStr; // Needed for parse::<T>()

// Assume your Rule enum and AssemblerParser struct are defined and generated by Pest
// #[derive(Parser)]
// #[grammar = "path/to/your_grammar.pest"] // Specify the path to your pest file
// struct AssemblerParser;

// #[derive(Rule_Helper)] // If you use rule_helper
// enum Rule { ... }

// Define data structures to represent your instructions
#[derive(Debug)]
struct Instruction {
  mnemonic: String,
  location: u16,
  operand1: Option<Operand>,
  operand2: Option<Operand>,
}

#[derive(Debug)]
enum Operand {
  Register(u8),
  Immediate(i32), // Use i32 for potentially signed numbers from your 'number' rule
  Address(u16),
  Label(String),
}

// --- Helper functions to parse operand strings ---

// Parses a register string like "R1" or "R10"
fn parse_register(reg_str: &str) -> Result<u8, String> {
  if !reg_str.starts_with('R') {
    return Err(format!(
      "Invalid register format: must start with 'R', got '{reg_str}'"
    ));
  }
  reg_str[1..]
    .parse::<u8>() // Parse the number part after 'R'
    .map_err(|e| format!("Invalid register number '{reg_str}': {e}"))
}

// Parses a number string (assuming decimal for simplicity, needs extension for hex)
fn parse_number(num_str: &str) -> Result<i32, String> {
  // Your 'number' rule allows a sign and uses your 'positive' rule.
  // This simple parse handles decimal signed integers.
  // You would need to add logic here to handle hexadecimal if allowed by your 'number' rule
  // (e.g., check for "0x" prefix and parse accordingly).
  i32::from_str(num_str).map_err(|e| format!("Invalid number format '{num_str}': {e}"))
}

// Parses an address string (assuming decimal for simplicity, needs extension for hex)
fn parse_address(addr_str: &str) -> Result<u16, String> {
  // Your 'address' rule defines the valid range 0-4096 and patterns.
  // This simple parse handles decimal.
  // You would need to add logic here to handle hexadecimal addresses like 0x008 if allowed.
  u16::from_str(addr_str).map_err(|e| format!("Invalid address format '{addr_str}': {e}"))
}

// --- Main function to process the parse tree ---

fn process_parse_tree(pairs: Pairs<Rule>) -> Result<Vec<Instruction>, String> {
  let mut location: u16 = 0;
  let mut instructions: Vec<Instruction> = Vec::new();

  // Get the single top-level Pair for the PROGRAM rule
  let mut program_pairs = pairs;
  let program_pair = program_pairs
    .next()
    .ok_or("Expected PROGRAM rule at top level")?;

  if program_pair.as_rule() != Rule::PROGRAM {
    return Err(format!(
      "Expected top-level rule PROGRAM, but got {:?}",
      program_pair.as_rule()
    ));
  }
  if program_pairs.next().is_some() {
    return Err("Expected only one top-level PROGRAM pair".to_string());
  }

  // Iterate over the inner pairs matched by the PROGRAM rule (these should be STMT rules)
  let statement_pairs = program_pair.into_inner();

  for stmt_pair in statement_pairs {
    println!("stmt_pair: {:?}", stmt_pair.as_str());
    // Each inner pair of PROGRAM should be a STMT rule based on your grammar PROGRAM = {(STMT)+}
    // If your PROGRAM rule allowed other things like EOL or WHITESPACE directly, you'd check here
    if stmt_pair.as_rule() != Rule::STMT {
      return Err(format!(
        "Expected STMT rule inside PROGRAM, but got {:?}",
        stmt_pair.as_rule()
      ));
    }

    // A STMT pair should have exactly one inner pair: either STMT_REG, STMT_IM, or STMT_ADDR
    let mut stmt_inner_pairs = stmt_pair.into_inner();
    let statement_type_pair = stmt_inner_pairs
      .next()
      .ok_or("Expected statement type rule inside STMT")?;

    if stmt_inner_pairs.next().is_some() {
      // This should not happen based on STMT = { STMT_REG | STMT_IM | STMT_ADDR }
      return Err(format!(
        "Unexpected multiple inner rules for STMT: {:?}",
        statement_type_pair.as_rule()
      ));
    }

    // Now, 'statement_type_pair' is the Pair for STMT_REG, STMT_IM, or STMT_ADDR
    // Since these rules are atomic, we get the full matched string from their span
    let statement_str = statement_type_pair.as_span().as_str().trim(); // Trim trailing EOL for easier splitting

    // --- Process the string based on the matched statement type ---
    let instruction = match statement_type_pair.as_rule() {
      Rule::STMT_REG => {
        // Format: REGISTER_KEYWORD WHITESPACE REGISTER WHITESPACE REGISTER EOL
        // Example string: "STO R1 R2"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 3 {
          return Err(format!(
            "Invalid STMT_REG format string: Expected 3 parts, got '{statement_str}'"
          ));
        }
        let mnemonic = parts[0].to_string();
        let reg1 = parse_register(parts[1])?;
        let reg2 = parse_register(parts[2])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Register(reg1)),
          operand2: Some(Operand::Register(reg2)),
        }
      }
      Rule::STMT_IM => {
        // Format: ("LOAD" | "CMP") WHITESPACE REGISTER WHITESPACE number EOL
        // Example string: "LOAD R10 10"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 3 {
          return Err(format!(
            "Invalid STMT_IM format string: Expected 3 parts, got '{statement_str}'"
          ));
        }
        let mnemonic = parts[0].to_string();
        let reg = parse_register(parts[1])?;
        let immediate = parse_number(parts[2])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Register(reg)),
          operand2: Some(Operand::Immediate(immediate)),
        }
      }
      Rule::STMT_ADDR => {
        // Format: ("JMP") WHITESPACE address EOL
        // Example string: "JMP 8" or "JMP 1024"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 2 {
          return Err(format!(
            "Invalid STMT_ADDR format string: Expected 2 parts, got '{statement_str}'"
          ));
        }
        let mnemonic = parts[0].to_string();
        let address = parse_address(parts[1])?;
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Address(address)),
          operand2: None, // JMP usually has only one operand
        }
      }
      Rule::STMT_LABEL => {
        // Format: ("JMP") WHITESPACE address EOL
        // Example string: "JMP 8" or "JMP 1024"
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 2 {
          return Err(format!(
            "Invalid STMT_ADDR format string: Expected 2 parts, got '{statement_str}'"
          ));
        }
        let mnemonic = parts[0].to_string();
        Instruction {
          mnemonic,
          location,
          operand1: Some(Operand::Label(parts[1].to_string())),
          operand2: None, // JMP usually has only one operand
        }
      }
      Rule::LABEL_DEC => {
        // Format: ASCII_ALPHA: EOL
        // Example loop:
        let parts: Vec<&str> = statement_str.split_whitespace().collect();
        if parts.len() != 1 {
          return Err(format!(
            "Invalid LABEL format string: Expected 1 part, got '{statement_str}'"
          ));
        }
        let mnemonic = parts[0].to_string();
        println!("label: {mnemonic}");
        // This does not get translated into byte code
        location -= 2;
        Instruction {
          mnemonic,
          location,
          operand1: None,
          operand2: None, // JMP usually has only one operand
        }
      }
      _ => {
        // This case should theoretically not be reached if STMT only alternates the above
        return Err(format!(
          "Unexpected rule type matched as statement type: {:?}",
          statement_type_pair.as_rule()
        ));
      }
    };
    location += 2;
    instructions.push(instruction);
  }

  Ok(instructions)
}

fn main() {
  let fibonacci_program_no_comments_asm = r#"LOAD R0 1
LOAD R1 1
LOAD R5 5
LOAD R6 1
SUB R5 R6
loop:
LOAD R3 R0
ADD R0 R1
LOAD R1 R3
STYX R5 R1
JMP loop
    "#;

  let parse_result = AssemblerParser::parse(Rule::PROGRAM, fibonacci_program_no_comments_asm);

  match parse_result {
    Ok(pairs) => {
      println!("Parse successful. Processing tree...");
      // Process the parse tree
      match process_parse_tree(pairs) {
        Ok(instructions) => {
          println!("Successfully extracted instructions:");
          for instr in instructions {
            println!("{instr:?}");
          }
        }
        Err(e) => {
          eprintln!("Error processing parse tree: {e}");
        }
      }
    }
    Err(e) => {
      eprintln!("Parse error: {e}");
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn number_works() {
    let p = AssemblerParser::parse(Rule::positive, "255").expect("Parse failed");
    assert_eq!(p.as_str(), "255");

    let p = AssemblerParser::parse(Rule::number, "0").expect("Parse failed");
    assert_eq!(p.as_str(), "0");
  }

  #[test]
  #[should_panic]
  fn positive_cant_parse_negative() {
    let _p = AssemblerParser::parse(Rule::positive, "-0").expect("Parse failed");
    panic!();
  }

  #[test]
  #[should_panic]
  fn no_minus_0() {
    let _p = AssemblerParser::parse(Rule::number, "-0").expect("Parse failed");
    panic!();
  }

  #[test]
  #[should_panic]
  fn bigger_than_255() {
    let _p = AssemblerParser::parse(Rule::number, "256").expect("Parse failed");
    panic!();
  }

  #[test]
  fn adress_works() {
    let p = AssemblerParser::parse(Rule::address, "256").expect("Parse failed");
    assert_eq!(p.as_str(), "256");
  }

  #[test]
  fn adress_4096_works() {
    let p = AssemblerParser::parse(Rule::address, "4096").expect("Parse failed");
    assert_eq!(p.as_str(), "4096");
  }

  #[test]
  fn adress_0_works() {
    let p = AssemblerParser::parse(Rule::address, "0").expect("Parse failed");
    assert_eq!(p.as_str(), "0");
  }

  #[test]
  #[should_panic]
  fn adress_negative_one_crashes() {
    let p = AssemblerParser::parse(Rule::address, "-1").expect("Parse failed");
    assert_eq!(p.as_str(), "-1");
  }

  #[test]
  fn test_whitespace_ignored() {
    let p = AssemblerParser::parse(Rule::WHITESPACE, " ").expect("Parse failed");
    assert_eq!(p.as_str(), "");
  }

  #[test]
  fn test_tab_ignored() {
    let p = AssemblerParser::parse(Rule::WHITESPACE, "\t").expect("Parse failed");
    assert_eq!(p.as_str(), "");
  }

  #[test]
  fn test_simple_newline_ignored() {
    let p = AssemblerParser::parse(Rule::EOL, "\n").expect("Parse failed");
    assert_eq!(p.as_str(), "\n");
  }

  #[test]
  fn test_simple_complex_ignored() {
    let p = AssemblerParser::parse(Rule::EOL, "\r\n").expect("Parse failed");
    assert_eq!(p.as_str(), "\r\n");
  }

  #[test]
  fn test_r0() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R0").expect("Parse failed");
    assert_eq!(p.as_str(), "R0");
  }

  #[test]
  fn test_r1() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R1").expect("Parse failed");
    assert_eq!(p.as_str(), "R1");
  }

  #[test]
  fn test_r2() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R2").expect("Parse failed");
    assert_eq!(p.as_str(), "R2");
  }

  #[test]
  fn test_r3() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R3").expect("Parse failed");
    assert_eq!(p.as_str(), "R3");
  }

  #[test]
  fn test_r4() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R4").expect("Parse failed");
    assert_eq!(p.as_str(), "R4");
  }

  #[test]
  fn test_r5() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R5").expect("Parse failed");
    assert_eq!(p.as_str(), "R5");
  }

  #[test]
  fn test_r6() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R6").expect("Parse failed");
    assert_eq!(p.as_str(), "R6");
  }

  #[test]
  fn test_r7() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R7").expect("Parse failed");
    assert_eq!(p.as_str(), "R7");
  }

  #[test]
  fn test_r8() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R8").expect("Parse failed");
    assert_eq!(p.as_str(), "R8");
  }

  #[test]
  fn test_r9() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R9").expect("Parse failed");
    assert_eq!(p.as_str(), "R9");
  }

  #[test]
  fn test_r10() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R10").expect("Parse failed");
    assert_eq!(p.as_str(), "R10");
  }

  #[test]
  fn test_r11() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R11").expect("Parse failed");
    assert_eq!(p.as_str(), "R11");
  }

  #[test]
  fn test_r12() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R12").expect("Parse failed");
    assert_eq!(p.as_str(), "R12");
  }

  #[test]
  fn test_r13() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R13").expect("Parse failed");
    assert_eq!(p.as_str(), "R13");
  }

  #[test]
  fn test_r14() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R14").expect("Parse failed");
    assert_eq!(p.as_str(), "R14");
  }

  #[test]
  fn test_r15() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R15").expect("Parse failed");
    assert_eq!(p.as_str(), "R15");
  }

  #[test]
  #[should_panic]
  fn test_r16() {
    let _p = AssemblerParser::parse(Rule::REGISTER, "R16").expect("Parse failed");
    panic!();
  }

  //Thanks chad
  macro_rules! test_keyword {
    ($name:ident, $input:expr) => {
      #[test]
      fn $name() {
        let p = AssemblerParser::parse(Rule::REGISTER_KEYWORD, $input).expect("Parse failed");
        assert_eq!(p.as_str(), $input);
      }
    };
  }

  test_keyword!(test_load, "LOAD");
  test_keyword!(test_add, "ADD");
  test_keyword!(test_sub, "SUB");
  test_keyword!(test_styx, "STYX");

  /////// RANDOM TESTS/////////////
  #[test]
  fn test_stmt_reg_sto_r1_r2_crlf() {
    let p = AssemblerParser::parse(Rule::STMT_REG, "STYX R1 R2\r\n").expect("Parse failed");
    assert_eq!(p.as_str(), "STYX R1 R2\r\n");
  }

  #[test]
  fn test_stmt_load_r1_r2() {
    let p = AssemblerParser::parse(Rule::STMT, "LOAD R1 R2\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R1 R2\n");
  }

  #[test]
  fn test_stmt_load_r3_r2() {
    let p = AssemblerParser::parse(Rule::STMT, "LOAD R3 R2\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R3 R2\n");
  }

  #[test]
  fn test_stmt_load_r9_r8() {
    let p = AssemblerParser::parse(Rule::STMT, "LOAD R9 R8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R9 R8\n");
  }

  #[test]
  fn test_register_r8() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R8").expect("Parse failed");
    assert_eq!(p.as_str(), "R8");
  }

  #[test]
  fn test_register_r10() {
    let p = AssemblerParser::parse(Rule::REGISTER, "R10").expect("Parse failed");
    assert_eq!(p.as_str(), "R10");
  }

  #[test]
  fn test_stmt_sto_r10_r8() {
    let p = AssemblerParser::parse(Rule::STMT, "STYX R10 R8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "STYX R10 R8\n");
  }

  #[test]
  fn test_stmt_load_r10_r8() {
    let p = AssemblerParser::parse(Rule::STMT, "LOAD R10 R8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R10 R8\n");
  }

  #[test]
  fn test_stmt_styx_r10_r8() {
    let p = AssemblerParser::parse(Rule::STMT, "STYX R10 R8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "STYX R10 R8\n");
  }

  #[test]
  fn test_stmt_im_load_r10_10() {
    let p = AssemblerParser::parse(Rule::STMT_IM, "LOAD R10 10\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R10 10\n");
  }

  #[test]
  fn test_stmt_im_load_r10_8() {
    let p = AssemblerParser::parse(Rule::STMT_IM, "LOAD R10 8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R10 8\n");
  }

  #[test]
  fn test_stmt_im_cmp_r10_8() {
    let p = AssemblerParser::parse(Rule::STMT_IM, "CMP R10 8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "CMP R10 8\n");
  }

  #[test]
  fn test_stmt_cmp_r10_8() {
    let p = AssemblerParser::parse(Rule::STMT, "CMP R10 8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "CMP R10 8\n");
  }

  #[test]
  fn test_stmt_add_r10_r8() {
    let p = AssemblerParser::parse(Rule::STMT, "ADD R10 R8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "ADD R10 R8\n");
  }

  #[test]
  fn test_stmt_addr_jmp_1024() {
    let p = AssemblerParser::parse(Rule::STMT_ADDR, "JMP 1024\n").expect("Parse failed");
    assert_eq!(p.as_str(), "JMP 1024\n");
  }

  #[test]
  fn test_stmt_jmp_1024() {
    let p = AssemblerParser::parse(Rule::STMT, "JMP 1024\n").expect("Parse failed");
    assert_eq!(p.as_str(), "JMP 1024\n");
  }

  // Placeholder for external string
  const FIB_PROG: &str = "LOAD R10 R8\nSTO R10 R8\n"; // Replace with actual `fibonacci_program_no_comments_asm`

  #[test]
  fn test_stmt_multiple() {
    let p = AssemblerParser::parse(Rule::STMT, FIB_PROG).expect("Parse failed");
    assert_eq!(p.as_str(), "LOAD R10 R8\n");
  }

  #[test]
  fn test_label_dec_loop() {
    let p = AssemblerParser::parse(Rule::LABEL_DEC, "loop:\n").expect("Parse failed");
    assert_eq!(p.as_str(), "loop:\n");
  }

  #[test]
  fn test_stmt_addr_jmp_8() {
    let p = AssemblerParser::parse(Rule::STMT_ADDR, "JMP 8\n").expect("Parse failed");
    assert_eq!(p.as_str(), "JMP 8\n");
  }

  #[test]
  fn test_stmt_addr_jmp_loop() {
    let p = AssemblerParser::parse(Rule::STMT_LABEL, "JMP loop\n").expect("Parse failed");
    assert_eq!(p.as_str(), "JMP loop\n");
  }

  /////////////// COMPLEX TESTS /////////////////////
  #[test]
  fn test_program_fibonacci() {
    let fibonacci_program_no_comments_asm = r#"LOAD R0 1
LOAD R1 1
LOAD R5 5
LOAD R6 1
SUB R5 R6
loop:
LOAD R3 R0
ADD R0 R1
LOAD R1 R3
STYX R5 R1
JMP loop
"#;

    let parse_result = AssemblerParser::parse(Rule::PROGRAM, fibonacci_program_no_comments_asm)
      .expect("Parse failed");
    assert_eq!(parse_result.as_str(), fibonacci_program_no_comments_asm);
  }
}
